### ISSUE TITLE
Create a script to automate vendor repo generation

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/ros_industrial_issues#16]
The specification for vendor repo layouts (see [here](http://wiki.ros.org/Industrial/Tutorials/SuggestedPackageLayoutNewRepositories) ) is meant to standardize the look and feel of repositories and ros packages.  It provides a framework that should support a variety of product types and variations.  The process of creating the desired directory structure as well as populating typical files (package xml, CMakeLists.txt, etc...) can be quite time consuming.  Much of the file content could be templated.  A well designed set of python scripts and/or xacro files could be used to automate production of these common parts.

**Comment by gavanderhoorn** [comment]
Seeing as we're trying to move away from hosting vendor repositories on `ros-industrial`, I'm closing this.

If/when interest in something like this returns, we can re-open.

**Comment by gavanderhoorn** [comment]
None-the-less: thanks for the initial work on this @shaun-edwards.
