### ISSUE TITLE
Configuring tests should be conditional (CATKIN_ENABLE_TESTING)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#18]
See [Configuring and running unit tests](http://docs.ros.org/hydro/api/catkin/html/howto/index.html#configuring-and-running-unit-tests) on the _catkin 0.5.81 documentation_ page.

Not sure whether the new `roslaunch` based tests should also be surrounded by a conditional.
- [x] [ABB](https://github.com/ros-industrial/abb)
- [x] [Fanuc](https://github.com/ros-industrial/fanuc)
- [x] [Industrial Core](https://github.com/ros-industrial/industrial_core)
- [x] [Motoman](https://github.com/ros-industrial/motoman)
<del>- [ ] [Universal](https://github.com/ros-industrial/universal_robot)</del> (there are no tests)

**Comment by gavanderhoorn** [comment]
The 'new style' support packages do this by default in their `CMakeLists.txt`, but repositories like `industrial_core` (`simple_message` fi) still unconditionally configure tests.

**Comment by gavanderhoorn** [comment]
Motoman done in ros-industrial/motoman#207.

**Comment by mathias-luedtke** [comment]
> To answer my own question: no, it should stay build_depend, as the contents of the roslaunch_add_file_check(..) catkin macro is needed at build-time

If it is wrapped with `CATKIN_ENABLE_TESTING`, it's a test depend in package format >=2.
Just like `rosunit` etc.

**Comment by gavanderhoorn** [comment]
@ipa-mdl: thanks for the hint, but the comment you replied to is from 2014 ;). Back then it had to stay a `build_depend`. In the meantime all / most pkgs have converted it to a `test_depend`.

**Comment by gavanderhoorn** [comment]
`industrial_core` done in ros-industrial/industrial_core#171.
