### ISSUE TITLE
ROS-Industrial Indigo Release

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/ros_industrial_issues#30]
@gavanderhoorn, @dpsolomon, @abubeck, @rkojcev, @phvass, @gomezc:

I have created milestones for indigo (see [here](https://github.com/ros-industrial/ros_industrial_issues/blob/master/indigo_roadmap.md)).  I'd like to utilize these milestones to track the indigo release progress.  Please update these milestones with due dates and issues to be addressed.  I'd like to aim for all indigo releases to be completed sometime in Q1, 2015

Since ROS Indigo is an LTS release(see [here](http://www.ros.org/news/2014/07/ros-indigo-igloo-released.html)), I would like ROS-Industrial to be considered an LTS.  This means the Indigo release should focus on the following following:
- Stability - significant/breaking changes should be avoided after initial Indigo release, plan wisely
- Documentation -  consider updating/cleaning up documentation
- Debian releases - all stable code should be released as a debian.  Any unstable/experimental code should remain a source release

Of course, this is all up for discussion (under this issue).  If you are no longer able to support the package/repo you have been assigned, please let me know.

Thank you all for you continued help and support.

**Comment by gavanderhoorn** [comment]
Indigo versions of al relevant packages have long since been available.

Closing.

Other releases should be tracked in new issues.
