### ISSUE TITLE
wiki: clicking footnote marks in supported_hardware table does not take reader to Notes section

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#31]
This could be due to an interaction with the version rocker, but clicking on the footnote marks on the [Industrial/supported_hardware](http://wiki.ros.org/action/fullsearch/Industrial/supported_hardware) page does not take me to the _2. Notes_ section. The url shown in the address bar of my browser does change, but nothing else happens.

This was reported by a user, in private email.

**Comment by gavanderhoorn** [comment]
This is still an issue, but from the lack of activity on ros-infrastructure/roswiki#112 I don't have much hope that this will be fixed.

#32 wants to update the `support_hardware` page, so perhaps we could come up with a way to structure the page -- if we keep it in its current form -- such that we can work-around the issue.

Perhaps the table could be removed, and each supported vendor could get its own section. That will also greatly simplify the wiki markup (moinmoin tables are hell).

**Comment by gavanderhoorn** [comment]
This is still an issue, but probably not something that is going to be fixed - or at least not in `roswiki`.

As suggested in https://github.com/ros-industrial/ros_industrial_issues/issues/31#issuecomment-321765100, we should probably move away from the current table-based overview and use (sub)sections. Those work much better with the version selectors at the top of the page.

Alternatively we could migrate all of this to Sphinx based docs. That would 'free' us from the limitations of MoinMoin completely.

**Comment by ipa-nhg** [comment]
Solved see http://wiki.ros.org/Industrial/supported_hardware
:+1: thank @ipa-led

**Comment by gavanderhoorn** [comment]
[diff](http://wiki.ros.org/action/info/Industrial/supported_hardware?action=diff&rev2=26&rev1=24).
