### ISSUE TITLE
Add 'doc' attributes to 'arg' elements in all launch files

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#33]
Since [ros_comm/PR#379](https://github.com/ros/ros_comm/pull/379) (released in roslaunch 1.11.1), the roslaunch `arg` element supports a `doc` attribute (currently undocumented). As one would expect, its function is to allow launch file authors to add (short) documentation strings to launch file arguments.

ROS-Industrial launch files should be updated to include doc strings in all launch files.

Packages:
- [x] ABB
- [x] Fanuc
- [x] `industrial_robot_client`
- [x] Motoman
- [ ] Universal Robot

**Comment by gavanderhoorn** [comment]
Fanuc done in ros-industrial/fanuc#168.

**Comment by gavanderhoorn** [comment]
PR for Motoman: ros-industrial/motoman#197.

**Comment by ipa-nhg-hd** [comment]
PR for industrial_robot_client: https://github.com/ros-industrial/industrial_core/pull/189

**Comment by gavanderhoorn** [comment]
ABB: ros-industrial/abb#143.

**Comment by gavanderhoorn** [comment]
PR for UR: ros-industrial/universal_robot#342.

Closing this as complete as the last PR may take some time before it gets merged.

**Comment by gavanderhoorn** [comment]
Thanks @ipa-hsd for your contributions :+1:
