### ISSUE TITLE
Fix project description on 'Robot Operating System' Wikipedia page

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#34]
The Wikipedia page on the [_Robot Operating System_](http://en.wikipedia.org/wiki/Robot_Operating_System) has this to say about ROS-Industrial:

> [ROS-Industrial](http://ros.org/wiki/Industrial) is a BSD-licensed “hardware-agnostic” software development program to create a Unified Robot Description Format (URDF) for industrial robots.

Which is at best incomplete.

This should be fixed.

Note: the [Wikipedia:Plain and simple conflict of interest guide](http://en.wikipedia.org/wiki/Wikipedia:Plain_and_simple_conflict_of_interest_guide).

**Comment by robinsonmm** [comment]
Yes the page it even references has a different description.

**Comment by robinsonmm** [comment]
I have updated Wikipedia. Please review.

**Comment by gavanderhoorn** [comment]
And as I expected: @robinsonmm's changes were reverted by a Wikipedia editor: [Robot_Operating_System&type=revision&diff=849848080&oldid=849834783](https://en.wikipedia.org/w/index.php?title=Robot_Operating_System&type=revision&diff=849848080&oldid=849834783). Nice that the comment included also adds:

> probable copyright violation; see https://rosindustrial.org/about/description

The [current version of the page](https://en.wikipedia.org/wiki/Robot_Operating_System#ROS-Industrial) does seem like an improvement over what it was in 2015 when I opened this issue though.

If we are ok with this for now then we can close this issue as `fixed`.

**Comment by gavanderhoorn** [comment]
ping @robinsonmm?

**Comment by robinsonmm** [comment]
I read it, it is an improvement. We do not want to be accused of plagiarizing ourselves after all.

**Comment by gavanderhoorn** [comment]
Ok, let's close this one then as resolved for now.

**Comment by gavanderhoorn** [comment]
Thanks for the 'review' @robinsonmm :+1: 

And your work of course .. although it got reverted ..
