### ISSUE TITLE
Update documentation to point to new Discourse category

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#53]
With the migration of the ROS-Industrial mailing list / Google group to the `ROS-Industrial` ROS Discourse category, all documentation and wiki pages directing users to post messages to `swri-ros-pkg-dev` needs to be updated.

I don't know of an easy way -- other than a Google search query (possibly restricted to a certain site with `site:...`) -- to find places that need to be updated.

Use this issue to track places that have already been or need to be updated in order to avoid duplication of effort.

---

Edit: updating this to show current state of things.

According to a Google search (`ros-industrial google group site:wiki.ros.org`) the following pages need to be updated on the wiki:

 - Industrial main wiki page:
   - [x] Contact us/Technical support ([diff](http://wiki.ros.org/Industrial?action=diff&rev1=70&rev2=71))
 - ABB:
   - [x] [abb](http://wiki.ros.org/abb) ([diff](http://wiki.ros.org/action/info/abb?action=diff&rev2=12&rev1=11))
   - [x] [abb_experimental](http://wiki.ros.org/abb_experimental) ([diff](http://wiki.ros.org/action/info/abb_experimental?action=diff&rev2=4&rev1=3))
 - Adept:
   - [x] [adept](http://wiki.ros.org/adept): [diff](http://wiki.ros.org/action/info/adept?action=diff&rev2=5&rev1=4)
 - Fanuc:
   - [x] Fanuc Troubleshooting page ([diff](http://wiki.ros.org/fanuc_driver/Troubleshooting?action=diff&rev1=33&rev2=34))
   - [x] `fanuc` wiki page ([diff](http://wiki.ros.org/fanuc/indigo?action=diff&rev1=9&rev2=10))
   - [x] `fanuc_experimental` wiki page ([diff](http://wiki.ros.org/fanuc_experimental?action=diff&rev1=26&rev2=27))
 - KUKA:
   - [x] `kuka_experimental` wiki page ([diff](http://wiki.ros.org/kuka_experimental?action=diff&rev1=8&rev2=9))
   - [x] KUKA Troubleshooting page ([diff](http://wiki.ros.org/kuka_rsi_hw_interface/Troubleshooting?action=diff&rev1=3&rev2=4))
 - Staübli:
   - [x] `staubli` wiki page ([diff](http://wiki.ros.org/staubli?action=diff&rev1=13&rev2=14))
   - [x] `staubli_experimental` wiki page ([diff](http://wiki.ros.org/staubli_experimental?action=diff&rev1=6&rev2=7))
 - Descartes:
   - [x] [descartes](http://wiki.ros.org/descartes): [diff](http://wiki.ros.org/action/info/descartes?action=diff&rev2=15&rev1=14)
 - Tutorials:
   - [x] [Industrial/Tutorials](http://wiki.ros.org/Industrial/Tutorials) ([diff](http://wiki.ros.org/action/info/Industrial/Tutorials?action=diff&rev2=24&rev1=23))
   - [x] [Industrial/Tutorials/IndustrialPullRequestReview](http://wiki.ros.org/Industrial/Tutorials/IndustrialPullRequestReview) ([diff](http://wiki.ros.org/action/info/Industrial/Tutorials/IndustrialPullRequestReview?action=diff&rev2=9&rev1=8))
 - Industrial Core pkgs:
   - [x] `simple_message` ([diff](http://wiki.ros.org/action/diff/simple_message?action=diff))
   - [x] [industrial_core](http://wiki.ros.org/industrial_core) ([diff](http://wiki.ros.org/action/info/industrial_core?action=diff&rev2=11&rev1=9))
   - [x] [industrial_msgs](http://wiki.ros.org/industrial_msgs): [diff](http://wiki.ros.org/action/info/industrial_msgs?action=diff&rev2=3&rev1=2)
   - [x] `industrial_robot_client`: [diff](http://wiki.ros.org/industrial_robot_client?action=diff&rev1=12&rev2=13)
   - [x] [industrial_robot_simulator](http://wiki.ros.org/industrial_robot_simulator): [diff](http://wiki.ros.org/action/info/industrial_robot_simulator?action=diff&rev2=8&rev1=7)
   - [x] [industrial_trajectory_filters](http://wiki.ros.org/industrial_trajectory_filters): [diff](http://wiki.ros.org/action/info/industrial_trajectory_filters?action=diff&rev2=11&rev1=10)
   - [x] [industrial_utils](http://wiki.ros.org/industrial_utils): [diff](http://wiki.ros.org/action/info/industrial_utils?action=diff&rev2=4&rev1=3)
 - Industrial MoveIt:
   - [x] [industrial_moveit](http://wiki.ros.org/industrial_moveit): [diff](http://wiki.ros.org/action/info/industrial_moveit?action=diff&rev2=3&rev1=2)
 - Motoman:
   - [x] [motoman](http://wiki.ros.org/motoman): [diff](http://wiki.ros.org/action/info/motoman?action=diff&rev2=30&rev1=29)
   - [x] [motoman_config](http://wiki.ros.org/motoman_config): [diff](http://wiki.ros.org/action/info/motoman_config?action=diff&rev2=3&rev1=2)
   - [x] [motoman_experimental](http://wiki.ros.org/motoman_experimental): [diff](http://wiki.ros.org/action/info/motoman_experimental?action=diff&rev2=4&rev1=3)
 - MT Connect:
   - [x] [mtconnect](http://wiki.ros.org/mtconnect): [diff](http://wiki.ros.org/action/info/mtconnect?action=diff&rev2=13&rev1=12)
 - Robotiq:
   - [x] [robotiq](http://wiki.ros.org/robotiq): [diff](http://wiki.ros.org/action/info/robotiq?action=diff&rev2=18&rev1=17)
 - Siemens:
   - [x] [siemens_cp1616](http://wiki.ros.org/siemens_cp1616): [diff](http://wiki.ros.org/action/info/siemens_cp1616?action=diff&rev2=31&rev1=30)
 - Universal Robot:
   - [x] [universal_robot](http://wiki.ros.org/universal_robot): [diff](http://wiki.ros.org/action/info/universal_robot?action=diff&rev2=29&rev1=28)

**Comment by gavanderhoorn** [comment]
Done:

 - KUKA Troubleshooting page ([here](http://wiki.ros.org/kuka_rsi_hw_interface/Troubleshooting?action=diff&rev1=3&rev2=4))
 - Fanuc Troubleshooting page ([here](http://wiki.ros.org/fanuc_driver/Troubleshooting?action=diff&rev1=33&rev2=34))

**Comment by minlingc** [comment]
more..
 - [ ]  http://wiki.ros.org/industrial_core --> point 3 contact us
 - [ ]  http://wiki.ros.org/universal_robot --> point 5 contact us
 - [ ]  http://wiki.ros.org/industrial_moveit--> point 3 contact us
 - [ ]  http://wiki.ros.org/Industrial/Tutorials --> Point 1

**Comment by gavanderhoorn** [comment]
I've merged your comment with the starting post @minlingc. You can actually edit it as well.

**Comment by gavanderhoorn** [comment]
I've created a wiki snippet that contains the correct text that we should include in the pages that need this, instead of editing the same text over and over.

See [industrial/contact_us_tech_support](http://wiki.ros.org/industrial/contact_us_tech_support).

I've updated the `fanuc` page with it: [diff](http://wiki.ros.org/action/diff/fanuc/indigo?action=diff).

Remove the current `Contact Us / Technical Support` section from a page and add:

```moinmoin
<<Include(industrial/contact_us_tech_support)>>
```
the snippet includes both the heading and the text, so no need to add / keep the heading.

**Comment by gavanderhoorn** [comment]
@130s: thanks for updating the `industrial_core` page on the wiki. Could I only ask you to use the includable snippet? That way we keep phrasing consistent and can update it in one go if we ever need to.

:+1:

**Comment by 130s** [comment]
Hope now it's updated properly. Nice to have such a template!

**Comment by gavanderhoorn** [comment]
Updated all pages listed in the OP.

If anything else comes up, post a new issue or comment on this one.
