### ISSUE TITLE
Travis integration broken?

### ISSUE THREAD

**Issue by mathias-luedtke** [ros-industrial/ros_industrial_issues#54]
At least for `industrial_ci` and `ros_canopen` the travis jobs get triggered, but Github does not show the status anymore.

**Comment by gavanderhoorn** [comment]
I'd updated some security settings for ros-industrial/docker#14. Apparently Travis was making use of the fact that we previously didn't have those settings enabled.

Should be fixed now.

**Comment by mathias-luedtke** [comment]
I have supposed something like this..
Works again, thanks!

**Comment by gavanderhoorn** [comment]
Must say I'm not a fan of Travis needing so much access to 'all' of our stuff though. But that is apparently something Github needs to fix.

**Comment by mathias-luedtke** [comment]
With the new Github Apps integration access can be granted for each repository.
At least for user repositories.
