### ISSUE TITLE
Migrate the package.xml files to format 2

### ISSUE THREAD

**Issue by ipa-nhg** [ros-industrial/ros_industrial_issues#56]
(or make more sense wait and migrate to format 3 directly http://www.ros.org/reps/rep-0149.html ?)

Lists of packages to be migrated:

- abb_experimental (ros-industrial/abb_experimental#115)
    - [x] abb_irb7600_support
    - [x] abb_ irb4600_support
    - [x] abb_irb1200_support
    - [x] abb_irb52_support
    - [x] abb_irb6650s_support
- industrial_core (ros-industrial/industrial_core#232)
    - [x] industrial_msgs
    - [x] industrial_core
    - [x] industrial_utils
    - [x] industrial_deprecated
    - [x] simple_message
    - [x] industrial_robot_client
    - [x] industrial_trajectory_filters
- industrial_moveit (https://github.com/ros-industrial/industrial_moveit/pull/102)
    - [x] constrained_ik
    - [x] industrial_moveit_benchmarking
    - [x] industrial_collision_detection
    - [x] industrial_moveit
- motoman (https://github.com/ros-industrial/motoman/pull/253)
    - [x] motoman_gp12_support
    - [x] motoman_gp7_support
    - [x] motoman_gp8_support
    - [x] motoman_mh50_support
    - [x] motoman_mh12_support
- motoman_experimental (ros-industrial/motoman_experimental#47)
    - [x] motoman_robot_pkg_gen
    - [x] motoman_experimental
    - [x] motoman_mh5_ikfast_manipulator_plugin
    - [x] motoman_mpl80_moveit_config
- staubli_experimental (ros-industrial/staubli_experimental#40)
    - [x] staubli_tx60_gazebo
    - [x] staubli_rx160_gazebo
    - [x] staubli_tx90_gazebo
    - [x] staubli_tx60_support
    - [x] staubli_experimental
    - [x] staubli_tx90_support
- staubli (ros-industrial/staubli#29)
    - [x] staubli_rx160_moveit_config
    - [x] staubli_rx160_moveit_plugins
    - [x] staubli_rx160_support
    - [x] staubli_resources
    - [x] staubli
- universal_robot (ros-industrial/universal_robot#439)
    - [x] ur_description
    - [x] ur3_moveit_config
    - [x] ur_msgs
    - [x] ur_bringup
    - [x] universal_robot
    - [x] ur_gazebo
    - [x] ur10_moveit_config
    - [x] ur5_moveit_config
    - [x] ur_kinematics
    - [x] ur_driver
 - stomp_ros:
    - [x] stomp_plugins
    - [x] stomp_moveit
    - [x] stomp_core
- robotiq (fixed, but repository was refactored, so pkgs have been changed)

**Comment by gavanderhoorn** [comment]
I think first getting everything to version 2 would be better. Changes to get to 3 are minimal, especially with the packages that we have: we don't have dependency groups, don't release into ROS2 (yet) and the ABI spec is nice, but not something of immediate concern.

**Comment by gavanderhoorn** [comment]
@ipa-nhg: could you perhaps update the issue with a list of pkgs that need to be updated?

**Comment by ipa-nhg** [comment]
Lists of packages to be migrated:

- industrial_core
    - [ ] industrial_msgs
    - [ ] industrial_core
    - [ ] industrial_utils
    - [ ] industrial_deprecated
    - [ ] simple_message
    - [ ] industrial_robot_client
    - [ ] industrial_trajectory_filters
- universal_robot
    - [ ] ur_description
    - [ ] ur3_moveit_config
    - [ ] ur_msgs
    - [ ] ur_bringup
    - [ ] universal_robot
    - [ ] ur_gazebo
    - [ ] ur10_moveit_config
    - [ ] ur5_moveit_config
    - [ ] ur_kinematics
    - [ ] ur_driver
- abb_experimental
    - [ ] abb_irb7600_support
    - [ ] abb_ irb4600_support
    - [ ] abb_irb1200_support
    - [ ] abb_irb52_support
    - [ ] abb_irb6650s_support
- motoman_experimental
    - [ ] motoman_robot_pkg_gen
    - [ ] motoman_experimental
    - [ ] motoman_mh5_ikfast_manipulator_plugin
    - [ ] motoman_mpl80_moveit_config
- staubli_experimental
    - [ ] staubli_tx60_gazebo
    - [ ] staubli_rx160_gazebo
    - [ ] staubli_tx90_gazebo
    - [ ] staubli_tx60_support
    - [ ] staubli_experimental
    - [ ] staubli_tx90_support
- robotiq
    - [ ] robotiq_s_model_articulated_gazebo
    - [ ] robotiq_modbus_rtu
    - [ ] robotiq_action_server
    - [ ] robotiq_s_model_visualization
    - [ ] robotiq_joint_state_publisher
    - [ ] robotiq_s_model_articulated_gazebo_plugins
    - [ ] robotiq_s_model_control
    - [ ] robotiq_c2_model_visualization
    - [ ] robotiq_s_model_articulated_msgs
    - [ ] robotiq_modbus_tcp
    - [ ] robotiq_force_torque_sensor
    - [ ] robotiq_ethercat
    - [ ] robotiq
    - [ ] robotiq_c_model_control
- staubli
    - [ ] staubli_rx160_moveit_config
    - [ ] staubli_rx160_moveit_plugins
    - [ ] staubli_rx160_support
    - [ ] staubli_resources
    - [ ] staubli
- motoman
    - [ ] motoman_gp12_support
    - [ ] motoman_gp7_support
    - [ ] motoman_gp8_support
    - [ ] motoman_mh50_support
    - [ ] motoman_mh12_support
- industrial_moveit
    - [ ] stomp_plugins
    - [ ] stomp_moveit
    - [ ] constrained_ik
    - [ ] stomp_test_kr210_moveit_config
    - [ ] industrial_moveit_benchmarking
    - [ ] industrial_collision_detection
    - [ ] stomp_test_support
    - [ ] industrial_moveit
    - [ ] stomp_core

**Comment by gavanderhoorn** [comment]
@ipa-nhg: thanks for the list.

For future reference: what command(s) did you use to find these packages?

**Comment by ipa-nhg** [comment]
I create a .rosinstall file with all the ros-industrial repos which contains ros packages, cloned from the rosinstall file and commanded:
`grep -R "<package>"`

I think will be useful push somewhere the rosinstall file (the industrial_metapackages repo could be an option or just create a new one industrial_basics? industrial_helper? industrial_helper_tools? ), also we can work on some basic bash script to check things like this.

**Comment by gavanderhoorn** [comment]
For anyone that wants to work on this during wrid19: please coordinate and announce the repository/packages that you're going to work on just so we can avoid duplication of effort.

**Comment by dejaniraai** [comment]
I will start with the industrial_core packages

**Comment by dejaniraai** [comment]
> I will start with the industrial_core packages

I have made a PR for this package. I will move this issue back to the unassigned so that someone can deal with the other packages.

**Comment by fmauch** [comment]
I'll start working on universal_robot

**Comment by Fern-and-dough** [comment]
I'll start working on abb_experimental

**Comment by dhled** [comment]
@ipa-nhg robotiq packages have through re-factoring. All package.xml have been updated to version 2 for kinetic devel.

**Comment by gavanderhoorn** [comment]
@ipa-led: I've updated the OP.

**Comment by Fern-and-dough** [comment]
Working on Staubli as well

**Comment by gavanderhoorn** [comment]
I've updated the OP to show the current state of things and unassigned the issue itself.

Thanks @wahlent, @fmauch, @dejaniraai, @Fern-and-dough and @trentwall for working on this and contributing your PRs! :+1:

**Comment by hsd-dev** [comment]
https://github.com/ros-industrial/stomp_ros already has format 2 for the `melodic-devel` branch

**Comment by hsd-dev** [comment]
https://github.com/ros-industrial/industrial_moveit/pull/102  
https://github.com/ros-industrial/motoman_experimental/pull/47  
https://github.com/ros-industrial/staubli_experimental/pull/40

**Comment by ipa-nhg** [comment]
seems to be completed, can this issue be closed?

**Comment by gavanderhoorn** [comment]
If all referenced PRs have been merged, then yes, it would seem this can be closed.

Thanks for the reminder.
