### ISSUE TITLE
Add license information badges to readme files

### ISSUE THREAD

**Issue by ipa-nhg** [ros-industrial/ros_industrial_issues#57]
see https://github.com/ros-industrial/fanuc/pull/244

**Comment by gavanderhoorn** [comment]
Example:

![sshot](https://user-images.githubusercontent.com/4550046/44096957-e505dd6c-9fdc-11e8-8777-8e21c94e83b5.png)

**Comment by gavanderhoorn** [comment]
Automatically crawling for licenses in ROS workspace / environment could be done perhaps using https://github.com/ros-infrastructure/rospkg/pull/143.

**Comment by 130s** [comment]
Although I've been happily using https://github.com/ros-infrastructure/rospkg/pull/143 (and its depended PR https://github.com/ros-infrastructure/rospkg/pull/133) in the internal repos for months, they aren't merged yet so need some setup. I'm happy to help if that's desired.

**Comment by gavanderhoorn** [comment]
@130s: thanks for the offer.

> they aren't merged yet so need some setup

are there any really involved steps, or would it "just" be a matter of merging the PR locally?

**Comment by 130s** [comment]
>>     they aren't merged yet so need some setup
>
> are there any really involved steps, or would it "just" be a matter of merging the PR locally?

I'd say it depends on the platform.
- Where dependency is only minimally installed, it usually needs some adhoc setting due to https://github.com/ros-infrastructure/rospkg/issues/142. 
  - In my experience this is the case for CI where I want to use base Docker image where dependency is only sparsely pre-installed.
- If dependency is well-installed, you may use the PR as is.
  - Without even merging, you can use just by setting `PATH` to `script` and `PYTHONPATH` to `src` folder in `rospkg`.

**Comment by gavanderhoorn** [comment]
This issue currently lacks an overview of the specific repositories that we'd like to add these badges too. That would first need to be added.

**Comment by hsd-dev** [comment]
https://github.com/ros-industrial/universal_robot/pull/436  
https://github.com/ros-industrial/abb/pull/170  
https://github.com/ros-industrial/motoman/pull/281  
https://github.com/ros-industrial/industrial_ci/pull/391  
https://github.com/ros-industrial/ros_canopen/pull/340  
https://github.com/ros-industrial/robotiq/pull/156  
https://github.com/ros-industrial/industrial_moveit/pull/95  
https://github.com/ros-industrial/industrial_training/pull/289

---
https://github.com/ros-industrial/noether/issues/44  
https://github.com/ros-industrial/industrial_moveit/issues/94  
https://github.com/ros-industrial/industrial_training/issues/288

**Comment by gavanderhoorn** [comment]
Thanks for the many PRs @ipa-hsd.

**Comment by gavanderhoorn** [comment]
I've unassigned you for now.

**Comment by ipa-nhg** [comment]
@ipa-hsd @gavanderhoorn I checked all the PRs and all of them are merged or closed because they were superseded by other commits.

I will close this issue for now. @ipa-hsd thanks a lot for your contribution 👍🏽

**Comment by hsd-dev** [comment]
There was some issue with https://github.com/ros-industrial/robotiq/pull/156 with multiple licenses being added. But seems like no action has been taken for it.

**Comment by gavanderhoorn** [comment]
`robotiq` has been inactive for a very long time. See my additions to the README: https://github.com/ros-industrial/robotiq/commit/a8c61490285fd5732e6e71694f636e61bb58f323.

Your PR was merged though I believe.
