### ISSUE TITLE
Packages for Melodic Migration

### ISSUE THREAD

**Issue by robinsonmm** [ros-industrial/ros_industrial_issues#59]
Proposed list for Packages to be Migrated to Melodic

Name - Status

- [x]  Industrial Core
     - [x]  PR Submitted
     - [x]  PR Merged
     - [x]  Release  
- [ ]  Industrial Calibration - Working Code
     - [x]  PR Submitted
     - [x]  PR Merged
     - [ ]  Release  
- [x]  ros_qtc_plugin - Done
     - [x]  PR Submitted
     - [x]  PR Merged
     - [x]  Release  
- [ ]  Basler/Astra/RealSense - not started
     - [ ]  PR Submitted
     - [ ]  PR Merged
     - [ ]  Release  
- [ ]  Robot Packages
     - [x]  Fanuc
         - [x]  PR Submitted
         - [x]  PR Merged
          - [x]  Release  
     - [ ]  Motoman
         - [x]  PR Submitted
         - [x]  PR Merged
          - [ ]  Release  
     - [x]  ABB
         - [x]  PR Submitted
         - [x]  PR Merged
          - [x]  Release  
     - [ ]  UR
         - [x]  PR Submitted
         - [x]  PR Merged
          - [ ]  Release  
- [ ]  Industrial MoveIt!
     - [x]  PR Submitted
     - [x]  PR Merged
     - [ ]  Release  
- [ ]  Descartes - not started
     - [x]  PR Submitted
     - [x]  PR Merged
     - [ ]  Release   
- [ ]  industrial_training
     - [x]  PR Submitted
     - [x]  PR Merged
     - [ ]  Release  
- [ ]  Godel - not stated
     - [ ]  PR Submitted
     - [ ]  PR Merged
     - [ ]  Release

**Comment by jrgnicho** [comment]
The robot drivers might be a bit difficult to validate but this looks like a manageable set of repos to migrate.

**Comment by robinsonmm** [comment]
Agreed. We have access to Universal, Yaskawa, ABB, and a Fanuc, though maybe not the best candidate. We also have a Kuka iiwa in house as well, and a working updated driver that should work for both Kinetic and Melodic. 

We will rely on community testing and submission of issues should problems arise for any additional or as problems arise for the variants of the makes (vintage and model).

**Comment by robinsonmm** [comment]
@gavanderhoorn @Levi-Armstrong has a release pending your review I believe on ros-i core.

**Comment by ipa-nhg** [comment]
@robinsonmm is this issues still relevant?

I reviewed the list of pending repositories from your old list and checked which of them have melodic support (best case a dedicated branch. And that is the result:

Industrial Core
- [x] Melodic Branch
- [x] Release

Industrial Calibration
- [x] Melodic Branch
- [ ] Release

Fanuc 
- [x] Melodic Branch
- [x] Release

Motoman
- [x] Melodic Branch (no but using kinetic-devel, no need)
- [ ] Release

ABB
- [x] Melodic Branch  (no but using kinetic-devel, no need)
- [x] Release

UR
- [x] Melodic Branch
- [ ] Release

Industrial MoveIt!
- [x] Melodic Branch
- [ ] Release

industrial_training
- [x] Melodic Branch
- [ ] Release

The repos Basler/Astra/RealSense, Descartes and Godel are not part of the ros-industrial organization. 

From my point of view, the only potential pending tasks for the issues are the release for melodic of the following repositories:

- motoman 
- universal_robot
- industrial_calibration
- industrial_moveit

But not sure if this is required for all of them, I suggest to create for each of them (if still relevant) a new issue and close this meta-issue.

**Comment by gavanderhoorn** [comment]
`industrial_moveit` will not see a release.

`industrial_calibration` is undergoing extensive refactoring.

`universal_robot` is already Melodic compatible.

and `motoman` as well.

I believe we can close this issue.

We can track progress for individual packages on the respective trackers.

**Comment by robinsonmm** [comment]
Thanks Gijs, agreed.
