### ISSUE TITLE
Should we add Probot/Stale to the ros-industrial organization?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_industrial_issues#60]
I am interested in adding this to several of the repositories that I maintain but wanted to reach out and see if it was ok to add this service to the organization. It does not force every repository to use it, only the ones that add a particular file to the repository similar to travis ci.

**Comment by Levi-Armstrong** [comment]
Here is the link: https://probot.github.io/apps/stale/

**Comment by gavanderhoorn** [comment]
It depends a bit on the permissions the app needs.

Personally I'm not a fan of allowing blanket access to all org data for apps, and some do ask quite a bit of access for no apparent reason.

**Comment by Levi-Armstrong** [comment]
I should of looked deeper but you can add it to individual repositories. The two permissions below are the only ones it requests.

- Read access to metadata and single file
- Read and write access to issues and pull requests

**Comment by Levi-Armstrong** [comment]
Is it OK if I add it to the trajopt, tesseract, and ros_qtc_plugin repository?

**Comment by gavanderhoorn** [comment]
If you're comfortable with that level of access, then sure, go ahead.

---

Edit: I haven't seen apps that can be added to single repositories of organisations though. They're typically added org-wide, then *enabled* for specific repositories.

**Comment by Levi-Armstrong** [comment]
This is what it shows me. It not very clear.

![image](https://user-images.githubusercontent.com/9803128/52886734-dc930e80-313a-11e9-86e0-14aa2cd45867.png)

**Comment by gavanderhoorn** [comment]
yes, that looks like you add it to the organisation and then activate/configure it for specific repositories.

That would be similar to what I've seen with other "apps" (like Travis).

Not sure there is anything that can be done about that though, short of integrating them manually (which for some reason is considered inefficient and is made rather difficult).

**Comment by Levi-Armstrong** [comment]
Oh, Is there any issue with the permission that have to be granted?

**Comment by gavanderhoorn** [comment]
> Oh, Is there any issue with the permission that have to be granted?

No, they're probably fine.

**Comment by gavanderhoorn** [comment]
Closing as it seems we've reached a conclusion.

@Levi-Armstrong: I'm not seeing any additional integrations. Did you end up installing Probot or Stale?
