### ISSUE TITLE
Update ROSindustrial.org/about/press

### ISSUE THREAD

**Issue by ipa-nhg** [ros-industrial/ros_industrial_issues#62]
https://rosindustrial.org/about/press

**Comment by ipa-thz** [comment]
@robinsonmm: 
I re-ordered the PRESS articles by years and kept the alphabetical order within the years.
The newest articles were from 2017, so I added 4 articles for 2018 and 2019, but we should add a lot more here.

**Comment by gavanderhoorn** [comment]
Seeing as there is no PR for this: @robinsonmm: could you review this and close the issue once we're all happy with it?

**Comment by robinsonmm** [comment]
I think this is a great start, and should we track down more, I for one am happy to keep adding! Closed.
