### ISSUE TITLE
Update https://rosindustrial.org/about/publications

### ISSUE THREAD

**Issue by ipa-thz** [ros-industrial/ros_industrial_issues#63]
with latest publications

**Comment by gavanderhoorn** [comment]
@ipa-thz: who would you like to review this?

As there is no PR, the review would consist of checking the page itself, of course.

Perhaps @robinsonmm?

**Comment by gavanderhoorn** [comment]
@ipa-thz: was this reviewed? If it was: closing the issue moves it to `completed` automatically. If it wasn't, we should move it back to `under review`.

**Comment by robinsonmm** [comment]
I checked it out. Looked good!

**Comment by gavanderhoorn** [comment]
If it's good enough then please close the issue so the task gets moved to `completed`.

**Comment by robinsonmm** [comment]
Yes, @ipa-thz will have to hit the close button. It is not available to me.

**Comment by gavanderhoorn** [comment]
Thanks @jrgnicho.

And thanks @robinsonmm for the review.
