### ISSUE TITLE
XACRO ERROR

### ISSUE THREAD

**Issue by Msamaritan** [ros-industrial/ros_industrial_issues#72]
xacro: in-order processing became default in ROS Melodic. You can drop the option.
substitution args not supported:  No module named 'rospkg'
when processing file: /home/cyber-mysterio/catkin_ws/src/turtlebot3/turtlebot3_description/urdf/turtlebot3_burger.urdf.xacro
RLException: Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '--inorder', '/home/cyber-mysterio/catkin_ws/src/turtlebot3/turtlebot3_description/urdf/turtlebot3_burger.urdf.xacro']] returned with code [2]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro --inorder $(find turtlebot3_description)/urdf/turtlebot3_$(arg model).urdf.xacro"/>
The traceback for the exception was written to the log file

I'm in ROS NOETIC ! ANYONE !

**Comment by gavanderhoorn** [comment]
Please do not cross-post (you'd already posted [here](https://github.com/ros-industrial/industrial_training/issues/220)), and please do not post issues with packages we do not maintain on our issue trackers.

This is an issue tracker for ROS-Industrial related packages and organisations.

For general questions about ROS, I'd suggest to post on ROS Answers.
